### ISSUE TITLE
how about put on pypi?

### ISSUE THREAD

**Issue by mo-han** [zhangchunlin/gfwlist2pac#1]
easier to install

**Comment by zhangchunlin** [comment]
Hi, there is one in pypi: https://pypi.org/project/gfwlist2pac/

**Comment by mo-han** [comment]
I believe that one is a out dated and python 2 only project

**Comment by zhangchunlin** [comment]
I will try to discuss with original maintainer.

**Comment by mo-han** [comment]
another name would be fine, such as gfwlist2pac-python3

**Comment by zhangchunlin** [comment]
Hi, have just uploaded 1.1.4 to https://pypi.org/project/gfwlist2pac/
